apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-test-small
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-test-small
  template:
    metadata:
      labels:
        app: gpt-test-small
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
      - name: inference-server
        image: vllm/vllm-openai:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
        command: [ "vllm", "serve" ]
        args:
        - facebook/opt-125m
        - --gpu-memory-utilization=0.5
        env:
        - name: PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-test-service
spec:
  selector:
    app: gpt-test-small
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
