apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-workload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gpu-workload
  template:
    metadata:
      labels:
        app: gpu-workload
    spec:
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: gpu-container
        image: busybox
        command: ["sleep", "3600"]
        resources:
          requests:
            nvidia.com/gpu: 1
            cpu: 1
            memory: 2Gi
          limits:
            nvidia.com/gpu: 1
            cpu: 2
            memory: 4Gi
