# Example: Custom Pod Identity Association for S3 access
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-access-sa
  namespace: default
---
# Pod Identity Association (created via Terraform or AWS CLI)
# aws eks create-pod-identity-association \
#   --cluster-name gpu-karpenter-cluster \
#   --namespace default \
#   --service-account s3-access-sa \
#   --role-arn arn:aws:iam::ACCOUNT:role/S3AccessRole

apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-app
  template:
    metadata:
      labels:
        app: s3-app
    spec:
      serviceAccountName: s3-access-sa  # Uses Pod Identity
      containers:
      - name: app
        image: amazon/aws-cli:latest
        command: ["sleep", "3600"]
        # No need for IRSA annotations - Pod Identity handles it automatically
